# Generated by Django 4.2.10 on 2026-03-14 14:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('pending', 'В ожидании'), ('archived', 'В архиве'), ('deleted', 'Удален')], db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения статуса')),
                ('status_comment', models.TextField(blank=True, verbose_name='Комментарий к изменению статуса')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, verbose_name='Дополнительный телефон')),
                ('website', models.URLField(blank=True, max_length=500, verbose_name='Веб-сайт')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('private_notes', models.TextField(blank=True, verbose_name='Приватные заметки')),
                ('type', models.CharField(choices=[('individual', 'Физическое лицо'), ('company', 'Юридическое лицо'), ('entrepreneur', 'Индивидуальный предприниматель')], db_index=True, default='individual', max_length=20, verbose_name='Тип клиента')),
                ('full_name', models.CharField(db_index=True, max_length=500, verbose_name='Полное наименование')),
                ('short_name', models.CharField(blank=True, max_length=255, verbose_name='Краткое наименование')),
                ('inn', models.CharField(blank=True, db_index=True, max_length=12, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Источник')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Изменил статус')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', 'status'], name='clients_cli_type_a989f2_idx'), models.Index(fields=['full_name'], name='clients_cli_full_na_193c54_idx'), models.Index(fields=['inn'], name='clients_cli_inn_b65595_idx'), models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx')],
            },
        ),
    ]
