# Generated by Django 4.2.10 on 2026-03-14 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название отчета')),
                ('type', models.CharField(choices=[('sales', 'Продажи'), ('clients', 'Клиенты'), ('tasks', 'Задачи'), ('contracts', 'Контракты')], max_length=20, verbose_name='Тип отчета')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='excel', max_length=20, verbose_name='Формат')),
                ('parameters', models.JSONField(default=dict, verbose_name='Параметры')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Файл отчета')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-created_at'],
            },
        ),
    ]
