# Generated by Django 6.0.4 on 2026-04-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_options_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия ссылки на оплату'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='contract',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID платежа в ЮKassa'),
        ),
    ]
