# Generated by Django 4.2.10 on 2026-03-13 23:22

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('role', models.CharField(choices=[('ADMIN', 'Администратор'), ('DIRECTOR', 'Директор'), ('MANAGER', 'Менеджер'), ('SALES', 'Продажник'), ('SUPPORT', 'Поддержка'), ('ACCOUNTANT', 'Бухгалтер'), ('VIEWER', 'Наблюдатель')], default='VIEWER', max_length=20, verbose_name='Роль')),
                ('department', models.CharField(blank=True, choices=[('MANAGEMENT', 'Руководство'), ('SALES', 'Продажи'), ('MARKETING', 'Маркетинг'), ('SUPPORT', 'Поддержка'), ('ACCOUNTING', 'Бухгалтерия'), ('IT', 'IT отдел'), ('HR', 'HR отдел')], max_length=20, verbose_name='Отдел')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('phone_work', models.CharField(blank=True, max_length=20, verbose_name='Рабочий телефон')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата найма')),
                ('fire_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('employee_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Табельный номер')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('telegram_notifications', models.BooleanField(default=False, verbose_name='Telegram уведомления')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Темная'), ('auto', 'Авто')], default='light', max_length=20, verbose_name='Тема оформления')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=50, verbose_name='Часовой пояс')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=10, verbose_name='Язык')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('passport_data', models.JSONField(blank=True, null=True, verbose_name='Паспортные данные')),
                ('emergency_contact', models.CharField(blank=True, max_length=255, verbose_name='Контакт для экстренных случаев')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон для экстренных случаев')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='Навыки')),
                ('education', models.JSONField(blank=True, default=list, verbose_name='Образование')),
                ('work_experience', models.JSONField(blank=True, default=list, verbose_name='Опыт работы')),
                ('certificates', models.JSONField(blank=True, default=list, verbose_name='Сертификаты')),
                ('notification_settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки уведомлений')),
                ('interface_settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки интерфейса')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'username'], name='accounts_us_email_301ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'department'], name='accounts_us_role_7483b9_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['employee_id'], name='accounts_us_employe_0cbd94_idx'),
        ),
    ]
