# Generated by Django 6.0.4 on 2026-04-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_accounts_us_email_301ffa_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Компания'),
        ),
    ]
