# Generated by Django 6.0.4 on 2026-04-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=10, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_notifications',
            field=models.BooleanField(default=False, verbose_name='Уведомления в Telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная')], default='light', max_length=20, verbose_name='Тема оформления'),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Europe/Moscow', max_length=50, verbose_name='Часовой пояс'),
        ),
    ]
