# Generated by Django 6.0.4 on 2026-04-19 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('direction', models.CharField(choices=[('request', 'Запрос'), ('response', 'Ответ'), ('webhook', 'Вебхук')], db_index=True, max_length=20)),
                ('endpoint', models.CharField(blank=True, max_length=255, verbose_name='Эндпоинт')),
                ('method', models.CharField(blank=True, max_length=10)),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='Данные запроса')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Данные ответа')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог API',
                'verbose_name_plural': 'Логи API',
                'ordering': ['-created_at'],
            },
        ),
    ]
