# Generated by Django 4.2.10 on 2026-03-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_email_301ffa_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_role_7483b9_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_employe_0cbd94_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fire_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_work',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_notifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='user',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='passport_data',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(blank=True, max_length=500, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Табельный номер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('MANAGER', 'Менеджер'), ('SALES', 'Продажник'), ('SUPPORT', 'Поддержка'), ('VIEWER', 'Наблюдатель')], default='VIEWER', max_length=20, verbose_name='Роль'),
        ),
    ]
