# Generated by Django 4.2.10 on 2026-03-14 14:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('pending', 'В ожидании'), ('archived', 'В архиве'), ('deleted', 'Удален')], db_index=True, default='active', max_length=20, verbose_name='Статус')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения статуса')),
                ('status_comment', models.TextField(blank=True, verbose_name='Комментарий к изменению статуса')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('private_notes', models.TextField(blank=True, verbose_name='Приватные заметки')),
                ('number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Номер договора')),
                ('type', models.CharField(choices=[('sale', 'Продажа'), ('service', 'Услуга'), ('maintenance', 'Обслуживание'), ('lease', 'Аренда'), ('consulting', 'Консалтинг')], default='service', max_length=20, verbose_name='Тип договора')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='Дата подписания')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оплачено')),
                ('payment_status', models.CharField(choices=[('not_paid', 'Не оплачен'), ('partially_paid', 'Частично оплачен'), ('paid', 'Оплачен'), ('overdue', 'Просрочен')], db_index=True, default='not_paid', max_length=20, verbose_name='Статус оплаты')),
                ('document', models.FileField(blank=True, null=True, upload_to='contracts/documents/', verbose_name='Файл договора')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='clients.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Изменил статус')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['number'], name='contracts_c_number_21c396_idx'), models.Index(fields=['client', 'status'], name='contracts_c_client__c0be66_idx'), models.Index(fields=['payment_status'], name='contracts_c_payment_0a743f_idx'), models.Index(fields=['start_date', 'end_date'], name='contracts_c_start_d_f953e0_idx')],
            },
        ),
    ]
