# Generated by Django 4.2.29 on 2026-04-08 16:33

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_all_contracts', 'Может просматривать все контракты'), ('can_edit_all_contracts', 'Может редактировать все контракты'), ('can_delete_all_contracts', 'Может удалять все контракты'), ('can_manage_payments', 'Может управлять оплатами')], 'verbose_name': 'Контракт', 'verbose_name_plural': 'Контракты'},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма платежа')),
                ('payment_date', models.DateField(default=datetime.date.today, verbose_name='Дата оплаты')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('bank_transfer', 'Банковский перевод'), ('card', 'Банковская карта'), ('electronic', 'Электронные деньги')], default='bank_transfer', max_length=20, verbose_name='Способ оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract', verbose_name='Контракт')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL, verbose_name='Кем добавлен')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ['-payment_date'],
            },
        ),
    ]
