# Generated by Django 6.0.4 on 2026-04-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_payment_expires_at_contract_payment_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirmation_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка для подтверждения оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время фактической оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='yookassa_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID платежа в ЮKassa'),
        ),
        migrations.AddField(
            model_name='payment',
            name='yookassa_status',
            field=models.CharField(blank=True, default='pending', max_length=50, verbose_name='Статус платежа в ЮKassa'),
        ),
    ]
